### PR TITLE
Add readme.md

### LINKED ISSUE #1: Add readme.md
README.md should cover:

* purpose of this repository
* topic-based guidance for contributors
* overview of the project technically
* overview of the project non-technical
* links to more resources and contributor handbook

### PR DESCRIPTION
**Pull request by BenJam**
Adds very simple overview of:

* why we're building Libraries.io
* how Libraries.io works
* how you can help

including links to other resources. Closes #1

### CODE REVIEW

**Comment by BenJam** [comment]
index.md was mv'd hmmm. It can be cp'd from readme.md id needed for docs.libraries.io.

**Comment by andrew** [comment]
I wonder if a symlink would work?

**Comment by andrew** [comment]
Looks like symlinks work in non-jekyll mode: https://github.com/s4y/gh-pages-symlink-test

**Comment by BenJam** [comment]
Those links appear to be broken. hmmm. Let's just try.

**Comment by andrew** [comment]
I wonder if GH pages will still turn the md into html with nojekyll

**Comment by andrew** [comment]
Looks like the symlink works but without jekyll it's just raw markdown files

**Comment by BenJam** [comment]
hmmm.

**Comment by andrew** [comment]
Not worth the faff for now, but we could get CI to build the pages to a gh-pages branch, for now I'd just cp readme.md to index.md

**Comment by BenJam** [comment]
yup.

**Comment by andrew** [comment]
Don't forget to remove the nojekyll file

**Comment by BenJam** [comment]
done https://github.com/librariesio/documentation/commit/660e036ed6502231b575d3b9081d020f03bb21ac

**Pull request merged**
