### PR TITLE
Improve wording and punctuation (part 2)

### PR DESCRIPTION
**Pull request by waldyrious**
Follow-up of #54. ~~Please don't merge yet, there's one more file to change.~~ (I'm doing this online, so I can't make a single commit, sorry.)

Update: this is now ready for review. By the way, isn't there any way to avoid duplicating text in three places? It's quite fragile and prone to become out-of-sync (and less convenient to edit :)).

### CODE REVIEW

**Comment by andrew** [comment]
Thanks for that, is this ready to merge now?

**Comment by waldyrious** [comment]
Yes (updated above).

**Comment by andrew** [comment]
👌

**Comment by andrew** [comment]
@waldyrious I think we're going to end up moving the docs back into the main repo fairly soon, most likely in the docs folder, which will be a good opportunity to remove that duplication.

**Pull request merged**
