### PR TITLE
Add SoureRank documentation

### LINKED ISSUE #4: overview of the project (non-technical)
Should be a guide focussed on non-developers that provides an overview of 

- [x] the mission
- [x] our philosophy
- [x] our strategy
- [ ] our roadmap (inc. funded goals/actions and future aspirations)
- [ ] a non-technical overview of the project's architecture and how the repo's relate to that

### LINKED ISSUE #11: SourceRank
I really like what SourceRank is turning out to be: a real manifestation of an idea that so many people have talked about for so long but nobody seems to have really followed through with. So congrats on pushing the concept forward.

I notice that for certain metrics like "Dependent Projects", the value is derived from "Logarithmic scale times two"...

I'd love to understand the motivations for these choices. Are the SourceRank "formulae" codified somewhere, or is the libraries.io codebase the best place to look?

screen shot 2017-02-08 at 4 39 38 pm

### PR DESCRIPTION
**Pull request by BenJam**
Also abandons the idea of a non-technical overview and combines into  more singular overview. 

closes #11 
closes #4

### CODE REVIEW

**Comment by andrew** [comment]
👍

**Comment by zeke** [comment]
Thanks for pulling this together, @BenJam 

Unfortunately there are some links to `sourcerank.md`, but that file doesn't exist. The new content actually lives in `overview.md`, so the links to `Sourcerank` are broken at this URL: https://docs.libraries.io/

**Comment by BenJam** [comment]
@zeke fixed up.

**Comment by zeke** [comment]
🤘

**Pull request merged**
